begin;

create table public.website_pages (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null references public.apps(id) on delete cascade,
  -- Ingestor must canonicalize URLs (including fragment removal) before upsert.
  url text not null check (url ~ '^https?://' and length(url) <= 2000),
  title text,
  content text,
  content_hash text check (content_hash ~ '^[0-9a-f]{64}$'),
  processed_content_hash text check (processed_content_hash ~ '^[0-9a-f]{64}$'),
  sync_status text not null default 'pending'
    check (sync_status in ('pending', 'syncing', 'ready', 'failed')),
  etag text,
  last_modified text,
  last_error text,
  last_checked_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (app_id, url),
  unique (app_id, id),
  check ((content is null) = (content_hash is null)),
  check (sync_status <> 'ready' or
    (content_hash is not null and processed_content_hash is not null
      and processed_content_hash = content_hash and last_synced_at is not null))
);

create table public.website_knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null,
  page_id uuid not null,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null check (length(btrim(content)) > 0),
  content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  source_content_hash text not null check (source_content_hash ~ '^[0-9a-f]{64}$'),
  search_document tsvector generated always as
    (to_tsvector('pg_catalog.simple'::regconfig, content)) stored,
  -- Provider-neutral placeholder; no embeddings are generated by this migration.
  -- A later vector migration can select dimension/model and add an ANN index.
  embedding real[],
  embedding_model text,
  embedded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (app_id, page_id) references public.website_pages(app_id, id) on delete cascade,
  unique (app_id, page_id, chunk_index),
  unique (app_id, page_id, content_hash),
  check ((embedding is null and embedding_model is null and embedded_at is null)
    or (embedding is not null and cardinality(embedding) > 0
      and array_ndims(embedding) = 1 and array_position(embedding, null) is null
      and embedding_model is not null and length(btrim(embedding_model)) > 0
      and embedded_at is not null))
);
create index website_pages_sync on public.website_pages(app_id, sync_status, last_checked_at);
create index website_chunks_search on public.website_knowledge_chunks using gin(search_document);

-- Gate ingestion even though service_role bypasses RLS. Deletes remain possible
-- after revocation, so a trusted backend can purge retained knowledge.
create function jai_private.guard_website_knowledge()
returns trigger language plpgsql security invoker set search_path = ''
as $$
begin
  if not public.app_has_capability(NEW.app_id, 'knowledge.website.read') then
    raise exception 'Website knowledge permission required' using errcode = '42501';
  end if;
  if TG_OP = 'UPDATE' then
    if NEW.app_id is distinct from OLD.app_id then
      raise exception 'Knowledge app is immutable' using errcode = '23514';
    end if;
    if TG_TABLE_NAME = 'website_knowledge_chunks' then
      if NEW.content is distinct from OLD.content or NEW.content_hash is distinct from OLD.content_hash then
        NEW.embedding := null;
        NEW.embedding_model := null;
        NEW.embedded_at := null;
      end if;
    end if;
  end if;
  NEW.updated_at := clock_timestamp();
  return NEW;
end;
$$;
revoke all on function jai_private.guard_website_knowledge() from public, anon, authenticated;
create trigger website_pages_guard before insert or update on public.website_pages
for each row execute function jai_private.guard_website_knowledge();
create trigger website_chunks_guard before insert or update on public.website_knowledge_chunks
for each row execute function jai_private.guard_website_knowledge();

alter table public.website_pages enable row level security;
alter table public.website_knowledge_chunks enable row level security;
revoke all on public.website_pages, public.website_knowledge_chunks from public, anon, authenticated;
grant select, insert, update, delete on public.website_pages, public.website_knowledge_chunks to service_role;
-- No browser policies. Existing tenant policies remain unchanged.

create function public.search_website_knowledge(p_app_id uuid, p_query text, p_limit integer default 8)
returns table (chunk_id uuid, page_id uuid, url text, title text, content text, rank real)
language plpgsql stable security invoker set search_path = ''
as $$
begin
  if not public.app_has_capability(p_app_id, 'knowledge.website.read') then
    raise exception 'Website knowledge permission required' using errcode = '42501';
  end if;
  return query
    select k.id, p.id, p.url, p.title, k.content,
      ts_rank(k.search_document, plainto_tsquery('pg_catalog.simple'::regconfig, p_query))
    from public.website_knowledge_chunks k
    join public.website_pages p on p.id = k.page_id and p.app_id = k.app_id
    where k.app_id = p_app_id and p.sync_status = 'ready'
      and p.content_hash = p.processed_content_hash
      and k.source_content_hash = p.content_hash
      and k.search_document @@ plainto_tsquery('pg_catalog.simple'::regconfig, p_query)
    order by 6 desc, k.id
    limit greatest(1, least(coalesce(p_limit, 8), 50));
end;
$$;
revoke all on function public.search_website_knowledge(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.search_website_knowledge(uuid, text, integer) to service_role;

-- Backend contract: derive app_id from trusted context, canonicalize URLs, and
-- compute SHA-256 over extracted content. If hash equals processed_content_hash,
-- update fetch/check metadata only. On change, replace page chunks and set the
-- processed hash, ready status and sync timestamp together in one transaction.
-- Retrieval must use the gated RPC, not service-role raw SELECT (which bypasses
-- RLS). Future semantic retrieval must apply the identical app/capability gates.
commit;
